// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6cIeoAmGJjNFr6QNZm_fua13Riwf_sqk',
    appId: '1:108173896607:web:1bb50419c02639ca3c2baa',
    messagingSenderId: '108173896607',
    projectId: 'chat-25d9f',
    authDomain: 'chat-25d9f.firebaseapp.com',
    storageBucket: 'chat-25d9f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2w713268hyaMjXNyybolU40iCQVzZYGc',
    appId: '1:108173896607:android:3f68462e368186043c2baa',
    messagingSenderId: '108173896607',
    projectId: 'chat-25d9f',
    storageBucket: 'chat-25d9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJEjPwMMrwGNQPpO7qL6kP-IiJ_kTrm4w',
    appId: '1:108173896607:ios:f8f6ccf9de9981063c2baa',
    messagingSenderId: '108173896607',
    projectId: 'chat-25d9f',
    storageBucket: 'chat-25d9f.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJEjPwMMrwGNQPpO7qL6kP-IiJ_kTrm4w',
    appId: '1:108173896607:ios:f8f6ccf9de9981063c2baa',
    messagingSenderId: '108173896607',
    projectId: 'chat-25d9f',
    storageBucket: 'chat-25d9f.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6cIeoAmGJjNFr6QNZm_fua13Riwf_sqk',
    appId: '1:108173896607:web:43cd62b38ed610483c2baa',
    messagingSenderId: '108173896607',
    projectId: 'chat-25d9f',
    authDomain: 'chat-25d9f.firebaseapp.com',
    storageBucket: 'chat-25d9f.firebasestorage.app',
  );
}
